title: Railway Videos
longtitle: Railway Videos XX
email: your-email@example.com
baseurl: "/railway-videos"
url: "https://github.com/aps831"
remote_theme: sighingnow/jekyll-gitbook
toc:
  enabled: true
  h_min: 1
  h_max: 3

plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - posts
  - others

page_width: 800px

destination: ./_site
incremental: false
regenerate: true
