title: Railway Videos
longtitle: Railway Videos XX
author: Philip Spratley
email: your-email@example.com
baseurl: "/railway-videos"
url: "https://github.com/aps831"
rss: RSS
remote_theme: sighingnow/jekyll-gitbook

version: 1.0
gitbook_version: 3.2.3

toc:
  enabled: true
  h_min: 1
  h_max: 3

favicon_path: /assets/gitbook/images/favicon.ico

markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - posts
  - others

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
